//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CdisMart_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.UserAuctions = new HashSet<Auction>();
            this.WinnedAuctions = new HashSet<Auction>();
            this.AuctionBids = new HashSet<AuctionRecord>();
        }
    
        public int UserId { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public string FullName { get; set; }
        public string Email { get; set; }
    
        public virtual ICollection<Auction> UserAuctions { get; set; }
        public virtual ICollection<Auction> WinnedAuctions { get; set; }
        public virtual ICollection<AuctionRecord> AuctionBids { get; set; }
    }
}
